/** Public numeric community ratings only; no upstream strategy text is reproduced.
 * Reviewed 2026-10-09. Matchup-update date is not published (stats date is separate).
 * Each row is the named hero's "countered by" rating: >5 favors other, <5 favors row hero.
 * Only publicly displayed non-neutral rows are captured; omitted pairs remain unknown.
 */
export const COUNTER_REVIEWED_AT = '2026-10-09'
export const COUNTER_SOURCE = 'https://counterpickgg.com'
export const counterSourceUrl = (hero: string) => COUNTER_SOURCE + '/heroes/' + (hero === 'jetpackcat' ? 'jetpack-cat' : hero === 'freja' ? 'freya' : hero)
export const COUNTER_ROWS: Record<string, [string, number][]> = {
  "ana": [["winston",9],["zarya",9],["dva",8],["sigma",8],["dmon",8],["genji",8],["tracer",8],["freja",8],["hanzo",7],["sombra",7],["widowmaker",7],["venture",7],["vendetta",7],["anran",7],["lucio",7],["kiriko",7],["wuyang",7],["doomfist",3],["ramattra",3],["wrecking-ball",3],["bastion",3],["mauga",2],["hazard",2],["mercy",2],["roadhog",1]],
  "anran": [["zarya",8],["mei",8],["pharah",8],["reaper",8],["symmetra",8],["moira",8],["kiriko",8],["jetpackcat",8],["orisa",7],["roadhog",7],["cassidy",7],["sombra",7],["baptiste",7],["brigitte",7],["mercy",7],["juno",7],["emre",4],["doomfist",3],["sigma",3],["genji",3],["widowmaker",3],["ana",3]],
  "ashe": [["winston",9],["dva",8],["genji",8],["sombra",8],["widowmaker",8],["venture",8],["vendetta",8],["wrecking-ball",7],["hazard",7],["hanzo",7],["tracer",7],["lucio",7],["kiriko",7],["illari",7],["junker-queen",3],["roadhog",3],["zarya",3],["domina",3],["bastion",3],["cassidy",3],["echo",3],["junkrat",3],["mei",3],["pharah",3],["torbjorn",3],["sierra",3],["brigitte",3],["mercy",2],["juno",2],["jetpackcat",2]],
  "baptiste": [["hanzo",7],["widowmaker",7],["mauga",6],["wrecking-ball",6],["cassidy",6],["dmon",3],["bastion",3],["junkrat",3],["pharah",3],["anran",3],["mercy",3],["jetpackcat",3],["echo",2]],
  "bastion": [["doomfist",8],["sigma",8],["hanzo",8],["reaper",8],["tracer",8],["sojourn",8],["wuyang",8],["ashe",7],["echo",7],["genji",7],["widowmaker",7],["freja",7],["ana",7],["baptiste",7],["emre",6],["reinhardt",3],["domina",3],["dmon",3],["pharah",3],["mercy",3],["zarya",2],["brigitte",2],["jetpackcat",2],["winston",1]],
  "brigitte": [["pharah",9],["ramattra",8],["reinhardt",8],["bastion",8],["echo",8],["symmetra",8],["jetpackcat",8],["mauga",7],["dmon",7],["ashe",7],["junkrat",7],["torbjorn",7],["widowmaker",7],["freja",7],["wuyang",7],["dva",3],["doomfist",3],["sigma",3],["winston",3],["genji",3],["sombra",3],["anran",3],["tracer",2],["shion",2]],
  "cassidy": [["freja",8],["junker-queen",7],["roadhog",7],["sigma",7],["dmon",7],["ashe",7],["hanzo",7],["widowmaker",7],["wuyang",7],["doomfist",3],["winston",3],["wrecking-ball",3],["echo",3],["junkrat",3],["reaper",3],["symmetra",3],["venture",3],["vendetta",3],["anran",3],["sierra",3],["shion",3],["lucio",3],["moira",3],["juno",3],["pharah",2],["sombra",2],["tracer",2],["mercy",2],["jetpackcat",2]],
  "dmon": [["ramattra",8],["mei",8],["torbjorn",8],["reinhardt",7],["bastion",7],["echo",7],["pharah",7],["reaper",7],["symmetra",7],["baptiste",7],["lifeweaver",7],["jetpackcat",7],["moira",4],["kiriko",4],["domina",3],["cassidy",3],["sombra",3],["shion",3],["brigitte",3],["mercy",3],["sigma",2],["zarya",2],["ana",2]],
  "domina": [["ramattra",8],["winston",8],["symmetra",8],["sojourn",8],["reinhardt",7],["zarya",7],["dmon",7],["ashe",7],["bastion",7],["mei",7],["reaper",7],["tracer",7],["widowmaker",7],["vendetta",7],["lucio",7],["pharah",3],["torbjorn",3],["mercy",3],["jetpackcat",2]],
  "doomfist": [["orisa",8],["roadhog",8],["echo",8],["pharah",8],["mauga",7],["cassidy",7],["junkrat",7],["mei",7],["sombra",7],["torbjorn",7],["anran",7],["sierra",7],["ana",7],["brigitte",7],["moira",7],["lifeweaver",7],["juno",7],["wuyang",7],["jetpackcat",7],["mizuki",7],["bastion",2],["widowmaker",2],["zenyatta",2]],
  "dva": [["zarya",8],["junker-queen",7],["roadhog",7],["mei",7],["symmetra",7],["brigitte",7],["mizuki",7],["echo",3],["sombra",3],["sojourn",3],["kiriko",3],["illari",3],["jetpackcat",3],["ashe",2],["hanzo",2],["junkrat",2],["pharah",2],["soldier-76",2],["freja",2],["sierra",2],["ana",2],["zenyatta",2],["widowmaker",1]],
  "echo": [["soldier-76",8],["emre",8],["baptiste",8],["dva",7],["zarya",7],["ashe",7],["cassidy",7],["widowmaker",7],["shion",7],["moira",7],["juno",7],["junker-queen",3],["reinhardt",3],["wrecking-ball",3],["dmon",3],["bastion",3],["mei",3],["pharah",3],["vendetta",3],["wuyang",3],["mizuki",3],["doomfist",2],["hazard",2],["hanzo",2],["reaper",2],["torbjorn",2],["tracer",2],["venture",2],["brigitte",2]],
  "emre": [["widowmaker",8],["dva",7],["sigma",7],["winston",7],["wrecking-ball",7],["genji",6],["venture",6],["vendetta",6],["anran",6],["bastion",4],["mei",3],["jetpackcat",3],["echo",2],["junkrat",2],["pharah",2]],
  "freja": [["dva",8],["winston",7],["zarya",7],["lucio",7],["illari",7],["roadhog",3],["bastion",3],["mei",3],["reaper",3],["symmetra",3],["torbjorn",3],["venture",3],["brigitte",3],["zenyatta",3],["cassidy",2],["junkrat",2],["ana",2]],
  "genji": [["mei",9],["symmetra",9],["moira",9],["winston",8],["zarya",8],["pharah",8],["torbjorn",7],["anran",7],["brigitte",7],["lucio",7],["emre",4],["sigma",3],["bastion",3],["soldier-76",3],["sojourn",3],["zenyatta",3],["lifeweaver",3],["ashe",2],["hanzo",2],["ana",2],["widowmaker",1]],
  "hanzo": [["dva",8],["winston",8],["wrecking-ball",8],["hazard",8],["echo",8],["genji",8],["vendetta",8],["lucio",8],["sigma",7],["pharah",7],["tracer",7],["juno",7],["mauga",3],["roadhog",3],["ashe",3],["cassidy",3],["mei",3],["symmetra",3],["torbjorn",3],["ana",3],["baptiste",3],["zenyatta",3],["illari",3],["bastion",2]],
  "hazard": [["pharah",9],["orisa",8],["roadhog",8],["echo",8],["ana",8],["mauga",7],["sigma",7],["zarya",7],["torbjorn",7],["zenyatta",7],["ashe",3],["shion",3],["hanzo",2],["widowmaker",2]],
  "illari": [["dva",7],["winston",7],["hanzo",7],["sombra",7],["widowmaker",7],["sojourn",7],["shion",7],["ashe",3],["reaper",3],["tracer",3],["freja",3],["mercy",3],["pharah",2]],
  "jetpackcat": [["mauga",9],["domina",8],["ashe",8],["bastion",8],["cassidy",8],["soldier-76",8],["sombra",8],["juno",8],["dva",7],["widowmaker",7],["sojourn",7],["emre",7],["baptiste",7],["doomfist",3],["junker-queen",3],["wrecking-ball",3],["dmon",3],["mei",3],["pharah",3],["reaper",3],["mizuki",3],["reinhardt",2],["junkrat",2],["symmetra",2],["vendetta",2],["anran",2],["brigitte",2]],
  "junker-queen": [["zarya",8],["pharah",8],["lucio",8],["kiriko",8],["orisa",7],["ashe",7],["junkrat",7],["widowmaker",7],["mercy",7],["jetpackcat",7],["mizuki",7],["dva",3],["cassidy",3],["winston",2]],
  "junkrat": [["pharah",9],["widowmaker",9],["dva",8],["mauga",8],["zarya",8],["freja",8],["emre",8],["mercy",8],["juno",8],["jetpackcat",8],["ashe",7],["cassidy",7],["soldier-76",7],["sombra",7],["baptiste",7],["doomfist",3],["junker-queen",3],["reinhardt",3],["brigitte",3]],
  "juno": [["winston",8],["ashe",8],["dva",7],["mauga",7],["zarya",7],["cassidy",7],["soldier-76",7],["sombra",7],["widowmaker",7],["moira",7],["doomfist",3],["reinhardt",3],["echo",3],["hanzo",3],["mei",3],["anran",3],["mercy",3],["zenyatta",3],["junkrat",2],["jetpackcat",2],["pharah",1]],
  "kiriko": [["dva",7],["pharah",7],["reinhardt",6],["winston",6],["wrecking-ball",6],["dmon",6],["ashe",3],["widowmaker",3],["venture",3],["ana",3],["junker-queen",2],["sombra",2],["anran",2],["sierra",2]],
  "lifeweaver": [["winston",8],["pharah",8],["vendetta",8],["mauga",7],["genji",7],["reaper",7],["venture",7],["doomfist",3],["dmon",3],["zarya",2]],
  "lucio": [["sombra",8],["mauga",7],["cassidy",7],["moira",7],["soldier-76",6],["sigma",3],["domina",3],["ashe",3],["genji",3],["widowmaker",3],["freja",3],["ana",3],["zenyatta",3],["junker-queen",2],["hanzo",2],["reinhardt",1]],
  "mauga": [["sigma",8],["reaper",8],["ana",8],["hanzo",7],["sojourn",7],["zenyatta",7],["doomfist",3],["reinhardt",3],["wrecking-ball",3],["hazard",3],["brigitte",3],["lucio",3],["mercy",3],["lifeweaver",3],["juno",3],["winston",2],["jetpackcat",1]],
  "mei": [["pharah",8],["ashe",7],["echo",7],["hanzo",7],["widowmaker",7],["freja",7],["emre",7],["mercy",7],["juno",7],["wuyang",7],["jetpackcat",7],["dva",3],["doomfist",3],["orisa",3],["zarya",3],["domina",3],["sombra",3],["tracer",3],["venture",3],["vendetta",3],["dmon",2],["anran",2],["genji",1]],
  "mercy": [["ashe",8],["cassidy",8],["soldier-76",8],["ana",8],["dva",7],["mauga",7],["domina",7],["dmon",7],["bastion",7],["sombra",7],["widowmaker",7],["shion",7],["baptiste",7],["illari",7],["juno",7],["junker-queen",3],["mei",3],["reaper",3],["tracer",3],["anran",3],["junkrat",2]],
  "mizuki": [["echo",7],["pharah",7],["jetpackcat",7],["sierra",6],["dmon",5],["dva",3],["doomfist",3],["junker-queen",3],["reinhardt",3],["vendetta",3]],
  "moira": [["symmetra",8],["roadhog",7],["cassidy",7],["torbjorn",7],["mauga",6],["dmon",6],["doomfist",3],["sigma",3],["wrecking-ball",3],["echo",3],["shion",3],["lucio",3],["juno",3],["sombra",2],["tracer",2],["anran",2],["sierra",2],["genji",1]],
  "orisa": [["zarya",8],["zenyatta",8],["sigma",7],["mei",7],["echo",6],["junker-queen",3],["ramattra",3],["winston",3],["wrecking-ball",3],["torbjorn",3],["vendetta",3],["anran",3],["doomfist",2],["reinhardt",2],["roadhog",2],["hazard",2]],
  "pharah": [["juno",9],["dva",8],["cassidy",8],["soldier-76",8],["sombra",8],["widowmaker",8],["emre",8],["shion",8],["illari",8],["zarya",7],["domina",7],["ashe",7],["bastion",7],["echo",7],["baptiste",7],["jetpackcat",7],["winston",3],["dmon",3],["hanzo",3],["torbjorn",3],["zenyatta",3],["kiriko",3],["mizuki",3],["doomfist",2],["junker-queen",2],["wrecking-ball",2],["genji",2],["mei",2],["reaper",2],["symmetra",2],["vendetta",2],["anran",2],["lifeweaver",2],["reinhardt",1],["hazard",1],["junkrat",1],["brigitte",1]],
  "ramattra": [["orisa",7],["ana",7],["zenyatta",7],["wuyang",7],["mauga",6],["winston",3],["torbjorn",3],["reinhardt",2],["domina",2],["dmon",2],["brigitte",2]],
  "reaper": [["echo",8],["pharah",8],["cassidy",7],["symmetra",7],["torbjorn",7],["freja",7],["mercy",7],["illari",7],["jetpackcat",7],["domina",3],["dmon",3],["sombra",3],["zenyatta",3],["lifeweaver",3],["mauga",2],["roadhog",2],["winston",2],["bastion",2],["anran",2]],
  "reinhardt": [["pharah",9],["lucio",9],["orisa",8],["ramattra",8],["symmetra",8],["torbjorn",8],["wuyang",8],["jetpackcat",8],["mauga",7],["bastion",7],["echo",7],["junkrat",7],["widowmaker",7],["juno",7],["mizuki",7],["sigma",3],["zarya",3],["domina",3],["dmon",3],["brigitte",2]],
  "roadhog": [["ana",9],["orisa",8],["reaper",8],["zenyatta",8],["ashe",7],["hanzo",7],["sojourn",7],["freja",7],["winston",3],["wrecking-ball",3],["cassidy",3],["symmetra",3],["vendetta",3],["anran",3],["shion",3],["moira",3],["doomfist",2],["hazard",2]],
  "shion": [["winston",8],["symmetra",8],["brigitte",8],["roadhog",7],["zarya",7],["hazard",7],["dmon",7],["cassidy",7],["torbjorn",7],["tracer",7],["moira",7],["sigma",3],["echo",3],["mercy",3],["zenyatta",3],["illari",3],["pharah",2]],
  "sierra": [["dva",8],["sigma",8],["sombra",8],["moira",8],["kiriko",8],["winston",7],["zarya",7],["ashe",7],["cassidy",7],["doomfist",3]],
  "sigma": [["zarya",9],["winston",8],["dmon",8],["sombra",8],["tracer",8],["reinhardt",7],["genji",7],["symmetra",7],["venture",7],["vendetta",7],["anran",7],["shion",7],["brigitte",7],["lucio",7],["moira",7],["orisa",3],["hazard",3],["cassidy",3],["hanzo",3],["emre",3],["zenyatta",3],["wuyang",3],["mauga",2],["bastion",2],["soldier-76",2],["sierra",2],["ana",2],["torbjorn",1]],
  "sojourn": [["dva",7],["zarya",7],["genji",7],["orisa",6],["sigma",6],["mauga",3],["roadhog",3],["torbjorn",3],["illari",3],["jetpackcat",3],["domina",2],["bastion",2]],
  "soldier-76": [["dva",8],["sigma",8],["winston",8],["vendetta",8],["genji",7],["junkrat",3],["juno",3],["echo",2],["pharah",2],["mercy",2],["jetpackcat",2]],
  "sombra": [["cassidy",8],["symmetra",8],["moira",8],["kiriko",8],["dva",7],["zarya",7],["dmon",7],["mei",7],["reaper",7],["torbjorn",7],["brigitte",7],["doomfist",3],["junkrat",3],["anran",3],["ana",3],["mercy",3],["zenyatta",3],["lifeweaver",3],["illari",3],["juno",3],["sigma",2],["wrecking-ball",2],["ashe",2],["pharah",2],["widowmaker",2],["sierra",2],["lucio",2],["jetpackcat",2]],
  "symmetra": [["zarya",8],["pharah",8],["wuyang",8],["jetpackcat",8],["roadhog",7],["cassidy",7],["hanzo",7],["freja",7],["dva",3],["sigma",3],["dmon",3],["reaper",3],["tracer",3],["venture",3],["vendetta",3],["reinhardt",2],["domina",2],["sombra",2],["anran",2],["shion",2],["brigitte",2],["moira",2],["genji",1]],
  "torbjorn": [["sigma",9],["echo",8],["orisa",7],["ramattra",7],["zarya",7],["domina",7],["ashe",7],["hanzo",7],["pharah",7],["sojourn",7],["doomfist",3],["wrecking-ball",3],["hazard",3],["genji",3],["reaper",3],["sombra",3],["venture",3],["shion",3],["brigitte",3],["moira",3],["reinhardt",2],["dmon",2],["tracer",2],["winston",1]],
  "tracer": [["cassidy",8],["echo",8],["pharah",8],["torbjorn",8],["brigitte",8],["moira",8],["mei",7],["symmetra",7],["mercy",7],["illari",7],["domina",3],["ashe",3],["hanzo",3],["shion",3],["sigma",2],["bastion",2],["widowmaker",2],["ana",2],["zenyatta",2]],
  "vendetta": [["pharah",8],["jetpackcat",8],["orisa",7],["roadhog",7],["cassidy",7],["echo",7],["mei",7],["symmetra",7],["mizuki",7],["emre",4],["sigma",3],["domina",3],["widowmaker",3],["ana",3],["hanzo",2],["soldier-76",2],["lifeweaver",2]],
  "venture": [["echo",8],["pharah",8],["cassidy",7],["mei",7],["symmetra",7],["torbjorn",7],["freja",7],["kiriko",7],["emre",4],["sigma",3],["soldier-76",3],["widowmaker",3],["lifeweaver",3],["ashe",2]],
  "widowmaker": [["dva",9],["winston",9],["genji",9],["doomfist",8],["wrecking-ball",8],["hazard",8],["sombra",8],["tracer",8],["venture",7],["vendetta",7],["anran",7],["lucio",7],["kiriko",7],["junker-queen",3],["reinhardt",3],["domina",3],["bastion",3],["cassidy",3],["echo",3],["mei",3],["ana",3],["baptiste",3],["brigitte",3],["zenyatta",3],["illari",3],["juno",3],["jetpackcat",3],["zarya",2],["ashe",2],["pharah",2],["emre",2],["junkrat",1]],
  "winston": [["bastion",9],["torbjorn",9],["junker-queen",8],["mauga",8],["reaper",8],["orisa",7],["ramattra",7],["roadhog",7],["cassidy",7],["pharah",7],["brigitte",7],["freja",3],["emre",3],["sierra",3],["illari",3],["sigma",2],["domina",2],["genji",2],["hanzo",2],["soldier-76",2],["shion",2],["zenyatta",2],["lifeweaver",2],["juno",2],["zarya",1],["ashe",1],["widowmaker",1],["ana",1]],
  "wrecking-ball": [["pharah",8],["sombra",8],["mauga",7],["orisa",7],["roadhog",7],["cassidy",7],["echo",7],["torbjorn",7],["ana",7],["moira",7],["jetpackcat",7],["ashe",3],["emre",3],["hanzo",2],["widowmaker",2]],
  "wuyang": [["zarya",8],["sigma",7],["echo",7],["dva",6],["winston",6],["doomfist",3],["ramattra",3],["cassidy",3],["mei",3],["ana",3],["brigitte",3],["reinhardt",2],["bastion",2],["symmetra",2]],
  "zarya": [["winston",9],["dmon",8],["bastion",8],["widowmaker",8],["lifeweaver",8],["reinhardt",7],["ashe",7],["mei",7],["hazard",3],["domina",3],["echo",3],["pharah",3],["sombra",3],["torbjorn",3],["sojourn",3],["freja",3],["sierra",3],["shion",3],["juno",3],["dva",2],["junker-queen",2],["orisa",2],["genji",2],["junkrat",2],["symmetra",2],["anran",2],["wuyang",2],["sigma",1],["ana",1]],
  "zenyatta": [["dva",8],["doomfist",8],["winston",8],["tracer",8],["venture",8],["sigma",7],["genji",7],["hanzo",7],["pharah",7],["reaper",7],["sombra",7],["widowmaker",7],["freja",7],["shion",7],["lucio",7],["juno",7],["mauga",3],["ramattra",3],["hazard",3],["orisa",2],["roadhog",2]],
}


// Official October reworks invalidate the old-kit pair explanations on the source table.
// Keep the captured observations for audit, but exclude both endpoints from recommendations.
export const COUNTER_PENDING_REWORK = new Set(['sombra', 'roadhog'])
